# Generated by Django 2.2.3 on 2019-07-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BabyShoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField()),
                ('context_1', models.TextField()),
                ('question_1', models.TextField()),
                ('word_limit_1', models.IntegerField()),
                ('context_2', models.TextField()),
                ('question_2', models.TextField()),
                ('word_limit_2', models.IntegerField()),
            ],
        ),
    ]
