# Generated by Django 2.2.3 on 2019-07-22 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BabyShoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField()),
                ('context_1', models.TextField()),
                ('question_1', models.TextField()),
                ('word_limit_1', models.IntegerField()),
                ('context_2', models.TextField()),
                ('question_2', models.TextField()),
                ('word_limit_2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('word_limit', models.IntegerField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='baby_shoes.BabyShoes')),
            ],
        ),
        migrations.CreateModel(
            name='Contexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='baby_shoes.BabyShoes')),
            ],
        ),
    ]
