# Generated by Django 2.2.3 on 2019-07-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby_shoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babyshoes',
            name='context_1',
        ),
        migrations.RemoveField(
            model_name='babyshoes',
            name='context_2',
        ),
        migrations.RemoveField(
            model_name='babyshoes',
            name='question_1',
        ),
        migrations.RemoveField(
            model_name='babyshoes',
            name='question_2',
        ),
        migrations.RemoveField(
            model_name='babyshoes',
            name='word_limit_1',
        ),
        migrations.RemoveField(
            model_name='babyshoes',
            name='word_limit_2',
        ),
    ]
