# Generated by Django 2.2.3 on 2019-07-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby_shoes', '0002_auto_20190722_1536'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contexts',
            new_name='Context',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
