# Generated by Django 2.2.3 on 2019-08-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresponse',
            name='views',
            field=models.TextField(default=''),
        ),
    ]
