# Generated by Django 2.2.4 on 2019-09-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0003_studentresponse_scroll_ups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='story',
            new_name='story_text',
        ),
    ]
