# Generated by Django 2.2.4 on 2019-09-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0004_auto_20190917_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='null@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='first',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='student',
            name='last',
            field=models.CharField(default='', max_length=70),
        ),
    ]
