# Generated by Django 2.2.4 on 2019-10-04 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0004_auto_20190917_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='context_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_responses', to='readings.Context'),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='question_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_responses', to='readings.Question'),
        ),
    ]
