# Generated by Django 2.2.4 on 2019-10-04 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0005_auto_20191004_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresponse',
            name='context',
        ),
        migrations.RemoveField(
            model_name='studentresponse',
            name='question',
        ),
    ]
