# Generated by Django 2.2.4 on 2019-10-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0006_auto_20191004_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresponse',
            old_name='context_fk',
            new_name='context',
        ),
        migrations.RenameField(
            model_name='studentresponse',
            old_name='question_fk',
            new_name='question',
        ),
    ]
