# Generated by Django 2.2.4 on 2019-10-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0007_auto_20191004_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='story',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
