# Generated by Django 2.2.4 on 2019-10-10 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0008_auto_20191004_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.TextField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='readings.Story')),
            ],
        ),
    ]
