# Generated by Django 2.2.4 on 2019-10-24 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    # For sqlite -- prevent from running in a transaction bc that breaks the renaming
    # see https://docs.djangoproject.com/en/2.2/howto/writing-migrations/#non-atomic-migrations
    atomic = False

    dependencies = [
        ('readings', '0008_auto_20191004_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentReadingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSegmentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Context',
            new_name='ContextPrototype',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='QuestionPrototype',
        ),
        migrations.RenameModel(
            old_name='Story',
            new_name='StoryPrototype',
        ),
        migrations.RenameModel(
            old_name='StudentResponse',
            new_name='StudentResponsePrototype',
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('sequence', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='readings.Document')),
            ],
        ),
    ]
