# Generated by Django 2.2.4 on 2019-10-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0008_auto_20191004_1339'),
        ('readings', '0005_auto_20190923_1529'),
    ]

    operations = [
    ]
