# Generated by Django 2.2.4 on 2019-10-24 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0009_auto_20191024_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('response_word_limit', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='studentreadingdata',
            name='document',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reading_data', to='readings.Document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentreadingdata',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reading_data', to='readings.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsegmentdata',
            name='reading_data',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='segment_data', to='readings.StudentReadingData'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsegmentdata',
            name='scroll_ups',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentsegmentdata',
            name='segment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='segment_data', to='readings.Segment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsegmentdata',
            name='views',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterUniqueTogether(
            name='segment',
            unique_together={('document', 'sequence')},
        ),
        migrations.CreateModel(
            name='SegmentQuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='readings.SegmentQuestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readings.Student')),
            ],
        ),
        migrations.AddField(
            model_name='segmentquestion',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='readings.Segment'),
        ),
        migrations.CreateModel(
            name='SegmentContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='readings.Segment')),
            ],
        ),
    ]
