# Generated by Django 2.2.4 on 2019-10-29 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0010_auto_20191024_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_questions', to='readings.Document')),
            ],
        ),
        migrations.AlterField(
            model_name='segment',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='DocumentQuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='readings.DocumentQuestion')),
                ('student_reading_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_responses', to='readings.StudentReadingData')),
            ],
        ),
    ]
