# Generated by Django 2.2.4 on 2019-10-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0010_auto_20191024_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
    ]
