# Generated by Django 2.2.4 on 2019-10-29 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0010_auto_20191024_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('response_word_limit', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='segmentquestion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='segmentquestion',
            name='response_word_limit',
        ),
        migrations.RemoveField(
            model_name='segmentquestion',
            name='text',
        ),
        migrations.AlterField(
            model_name='segment',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='segmentquestion',
            name='question_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='readings.Question'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DocumentQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='readings.Question')),
                ('is_overview_question', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='readings.Document')),
            ],
            bases=('readings.question',),
        ),
    ]
