# Generated by Django 2.2.4 on 2019-11-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0011_auto_20191029_1645'),
        ('readings', '0011_auto_20191025_1836'),
    ]

    operations = [
    ]
