# Generated by Django 2.2.4 on 2019-11-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0011_auto_20191029_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentquestion',
            name='response_word_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='segmentquestion',
            name='response_word_limit',
            field=models.IntegerField(null=True),
        ),
    ]
