# Generated by Django 2.2.4 on 2019-11-01 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0012_merge_20191101_1928'),
        ('readings', '0012_auto_20191101_1431'),
    ]

    operations = [
    ]
