# Generated by Django 2.2.4 on 2019-11-10 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0013_auto_20191110_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentquestionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_question', to='readings.SegmentQuestion'),
        ),
    ]
