# Generated by Django 2.2.4 on 2019-11-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0014_auto_20191110_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentquestionresponse',
            name='response',
            field=models.TextField(),
        ),
    ]
