# Generated by Django 2.2.4 on 2019-11-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0017_auto_20191110_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentquestionresponse',
            name='response_segment',
            field=models.IntegerField(default=1),
        ),
    ]
