# Generated by Django 2.2.4 on 2019-11-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0018_auto_20191115_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentquestionresponse',
            name='response_segment',
            field=models.IntegerField(default=1),
        ),
    ]
