# Generated by Django 2.2.4 on 2019-11-19 16:51

from django.db import migrations, models
from django.db import transaction
import django.db.models.deletion


def student_to_studentprototype(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Student = apps.get_model("readings", "Student")
    StudentPrototype = apps.get_model("readings", "StudentPrototype")

    db_alias = schema_editor.connection.alias
    students = Student.objects.using(db_alias).all()

    for student in students:
        responses = student.student_responses.all()
        if responses:
            sp = StudentPrototype()
            sp.save()
            for response in responses:
                response.student_id = sp.id
                response.save()


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0019_documentquestionresponse_response_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPrototype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),

        migrations.RunPython(student_to_studentprototype),

        migrations.AlterField(
            model_name='studentresponseprototype',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_responses', to='readings.StudentPrototype'),
        ),

    ]
