# Generated by Django 2.2.4 on 2019-11-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0020_auto_20191119_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentquestion',
            name='require_evidence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentquestionresponse',
            name='evidence',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='segmentquestion',
            name='require_evidence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='segmentquestionresponse',
            name='evidence',
            field=models.TextField(default='[]'),
        ),
    ]
