# Generated by Django 2.2.4 on 2019-11-25 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0021_auto_20191122_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentquestionresponse',
            name='submission_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='segmentquestionresponse',
            name='submission_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentreadingdata',
            name='last_updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentreadingdata',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsegmentdata',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
