# Generated by Django 2.2.4 on 2019-11-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0022_auto_20191125_1405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SegmentContext',
        ),
    ]
