# Generated by Django 2.2.4 on 2019-11-27 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0023_delete_segmentcontext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentquestion',
            name='response_word_limit',
        ),
        migrations.RemoveField(
            model_name='segmentquestion',
            name='response_word_limit',
        ),
    ]
