# Generated by Django 2.2.4 on 2019-11-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0024_auto_20191127_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentquestion',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='segmentquestion',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
    ]
