# Generated by Django 2.2.4 on 2019-12-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0026_writeup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeup',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
