# Generated by Django 2.2.3 on 2019-07-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby_shoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='story_text',
            new_name='story',
        ),
    ]
