# Generated by Django 2.2.3 on 2019-07-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_shoes', '0004_remove_student_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
